### ISSUE TITLE
add new parameter to influx point data

### ISSUE THREAD

**Issue by fm-foo** [fm-foo/Iot-smartPlant-Portal#3]
add new parameter called "deviceID" 

the json string that the subscriber receives will have a JsonProperty = "device_id"

**Comment by ZeXVex** [comment]
Have add device id to the new brance Nicolai-02

**Comment by fm-foo** [comment]
cool can i closed this isuue?

**Comment by ZeXVex** [comment]
yes that you can or ill do it
